language: c

env:
    - NUMPY_VERSION=1.8 OMP_NUM_THREADS=2

cache:
    - directories:
        - ${TRAVIS_BUILD_DIR}/depends

addons:
    apt:
        packages:
            - libopenmpi-dev
            - openmpi-bin
            - libgsl0-dev

install:
    - cp Makefile.travis Makefile.local
    - make

script:
    - pushd tests
    - sh runtest.sh
    - test -f pm/powerspec-1.0000.txt
    - test -f pm/snp00100_1.0000.bin.00
    - test -f cola/powerspec-1.0000.txt
    - test -f cola/snp00100_1.0000.bin.00
    - popd
